name: Install Docker

on:
  push

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo chmod 666 /var/run/docker.sock
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      