env:
  browser: true
  commonjs: true
  es2023: true
extends:
  - eslint:recommended
  # - plugin:@typescript-eslint/recommended
# parser: '@typescript-eslint/parser'
parser: 'esprima'
parserOptions:
  ecmaVersion: latest
# plugins:
#   - '@typescript-eslint'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-unused-vars:
    - warn
  # "@typescript-eslint/no-unused-vars":
  #   - warn
